<a href="https://colab.research.google.com/github/dayeong918/pdm011/blob/main/numpy_2_array2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## concatenate()를 이용한 배열 결합
> [numpy 배열 합치기, concatenate 함수](https://m.blog.naver.com/PostView.nhn?blogId=qbxlvnf11&logNo=221490583222&categoryNo=0&proxyReferer=https%3A%2F%2Fwww.google.com%2F)

In [1]:
import numpy as np

In [2]:
ar1 = np.array(range(1,5)).reshape(2,2)
ar1

array([[1, 2],
       [3, 4]])

In [3]:
ar1.shape

(2, 2)

In [4]:
ar2 = np.array(range(5,11)).reshape(2,3)  # np.array(range(5,11)).reshape(-1,3)
ar2

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
ar2.shape  # 2 X 3 array

(2, 3)

In [6]:
print(ar1)
print(ar2)

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]


## concatenate()를 이용한 배열 합치기


- concatenate(array1, array2, axis = 0)
- concatenate(array1, array2, axis = 1)
- concatenate(array1, array2, axis = None)

In [ ]:
np.concatenate((ar1,ar1), axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [7]:
np.concatenate((ar1,ar1,ar1), axis=0)

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [ ]:
np.concatenate((ar1,ar1), axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [ ]:
np.concatenate((ar1,ar1), axis=None)

array([1, 2, 3, 4, 1, 2, 3, 4])

### ar2에 대하여도 배열합치기를 해보시오.

In [ ]:
# Your code here!
print(np.concatenate((ar2,ar2), axis=None))
print(np.concatenate((ar2,ar2), axis=0))
print(np.concatenate((ar2,ar2), axis=1))

[ 5  6  7  8  9 10  5  6  7  8  9 10]
[[ 5  6  7]
 [ 8  9 10]
 [ 5  6  7]
 [ 8  9 10]]
[[ 5  6  7  5  6  7]
 [ 8  9 10  8  9 10]]


### Error in concatenation

In [ ]:
np.concatenate((ar1,ar2), axis=0)

#ValueError: all the input array dimensions for the concatenation axis must match
#exactly, but along dimension 1, the array at index 0 has size 2 and the array at
#index 1 has size 3

ValueError: ignored

> ar1의 열의 갯수 == ar2의 열의 갯수

In [ ]:
ar1.shape, ar2.shape

((2, 2), (2, 3))

In [ ]:
ar2.T.shape

(3, 2)

In [ ]:
np.concatenate((ar1,ar2.T), axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  8],
       [ 6,  9],
       [ 7, 10]])

### concatenate(array1, array2, axis = 1)

In [ ]:
np.concatenate((ar1,ar2), axis=1)

array([[ 1,  2,  5,  6,  7],
       [ 3,  4,  8,  9, 10]])



---



---



## [복습] numpy 배열 연산: broadcasting
> [파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자](https://blog.naver.com/qbxlvnf11/221509303462)

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b   # elementwise multiplication
# [출처] 파이썬 Numpy 라이브러리 (5) Broadcasting|작성자 예비개발자


array([2., 4., 6.])

In [ ]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b   # broadcasted multiplication


array([2., 4., 6.])

> 차원이 다른 두 개의 피연산자를 산술 연산할 때는 원래 연산이 불가능합니다.
하지만, 연산이 가능하도록 배열 b가 브로드캐스팅이 되어 numpy array ([2.0, 2.0, 2.0])으로 확장됩니다.

### 2차원 broadcasting

In [ ]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])

a + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [ ]:
(a+b).shape

(4, 3)

In [ ]:
from numpy import array, newaxis
a = array([0.0,10.0,20.0,30.0])
b = array([1.0,2.0,3.0])
c = a[:,newaxis]+b
c

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [ ]:
c.shape

(4, 3)

## numpy statistics
> [numpy: 기술 통계](https://datascienceschool.net/01%20python/03.04%20%EA%B8%B0%EC%88%A0%20%ED%86%B5%EA%B3%84.html)
- min(), max()
- mean(), median(), var(), std()

In [9]:
a = np.array(list(range(1,10)))
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# np.min, np.max
import numpy as np
a.min(), a.max()

(1, 9)

In [11]:
# array.min(), array.max()
np.min(a), np.max(a)

(1, 9)

In [12]:
# mean() and median()
a.mean(), np.median(a)

(5.0, 5.0)

In [13]:
# var(), std()
a.var(), a.std()

(6.666666666666667, 2.581988897471611)

In [14]:
np.var(a), np.std(a)

(6.666666666666667, 2.581988897471611)

## 2차원 배열의 기술 통계
- axis = 0
- axis = 1

In [15]:
d2arr = np.arange(1,10).reshape(-1,3)
d2arr 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
d2arr.max()

9

In [18]:
d2arr.max(axis=0) , d2arr.max(axis=1)

(array([7, 8, 9]), array([3, 6, 9]))

In [19]:
print(d2arr.min(axis=None))
print(d2arr.min(axis=0))
print(d2arr.min(axis=1))

1
[1 2 3]
[1 4 7]


## [DIY: 도전과제]
- axis = None, 1, 2 에 따른 평균을 구하시오.

In [38]:
# Your code here!
import numpy as np

d3arr = np.arange(1,9)
b = d3arr.reshape(2,2,2) # 3차원 배열

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4.5
[[2. 3.]
 [6. 7.]]
[[1.5 3.5]
 [5.5 7.5]]


#### axis = None

In [42]:
print(b.mean(axis=None)) 

4.5


#### axis = 1

In [40]:
print(b.mean(axis=1)) 

[[2. 3.]
 [6. 7.]]


#### axis = 2

In [41]:
print(b.mean(axis=2))

[[1.5 3.5]
 [5.5 7.5]]
