<a href="https://colab.research.google.com/github/dayeong918/pdm011/blob/main/numpy/numpy_3_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy
## random 서브모듈
> [데이터싸이언스 스쿨:난수발생](https://datascienceschool.net/01%20python/03.05%20%EB%82%9C%EC%88%98%20%EB%B0%9C%EC%83%9D%EA%B3%BC%20%EC%B9%B4%EC%9A%B4%ED%8C%85.html)

In [1]:
import numpy as np

## 난수 생성
> NumPy의 random 서브모듈은 난수를 생성하는 다양한 명령을 제공.

- rand: 0부터 1사이의 균일 분포 (uniform distribution)
- randn: 가우시안 표준 정규 분포 (normal distribution, Gaussian)
- randint: 균일 분포의 정수 난수 (uniform int)

> randn()은 평균 0, 표준편차 1 인 가우시안 정규분포를 생성.

### rand: 0부터 1사이의 균일 분포 (uniform distribution)

In [2]:
np.random.rand(5)

array([0.51510254, 0.27661799, 0.14872175, 0.43253575, 0.21579139])

In [3]:
np.random.rand(5)

array([0.31836409, 0.7150868 , 0.04793603, 0.54327006, 0.90326875])

### randn: 가우시안 표준 정규 분포 (normal distribution, Gaussian)

In [4]:
np.random.randn(5)

array([-1.78304332, -0.22944645, -0.25710452, -1.24532953,  1.2551463 ])

### randint: 균일 분포의 정수 난수 (uniform int)
- numpy.random.randint(low, high=None, size=None, dtype='l')

In [5]:
np.random.randint(5)

1

In [6]:
np.random.randint(5,9) 

8

In [7]:
np.random.randint(0,10,5)

array([0, 4, 2, 2, 5])

In [8]:
np.random.randint(0,10,5)

array([3, 7, 4, 1, 9])

---

## 난수 생성 seed 설정
- numpy.random.seed(seed=None)
- np.random.seed(number)

In [9]:
np.random.seed()

In [10]:
np.random.rand(5)

array([0.73408808, 0.14973226, 0.23327201, 0.74259066, 0.39109759])

In [11]:
np.random.rand(5)

array([0.47418598, 0.38914814, 0.58091373, 0.03569594, 0.4956397 ])

### 동일한 무작위수 생성
- seed를 고정하고 무작위수 생성

In [26]:
np.random.seed(1234)

In [13]:
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

In [14]:
np.random.rand(5)

array([0.27259261, 0.27646426, 0.80187218, 0.95813935, 0.87593263])

In [15]:
np.random.seed(1234)

In [16]:
np.random.rand(5)

array([0.19151945, 0.62210877, 0.43772774, 0.78535858, 0.77997581])

### seed 고정 후에 randint(5)

In [17]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [18]:
np.random.randint(1,10,5)

array([6, 3, 7, 4, 1])

In [19]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [22]:
np.random.seed(5678)
np.random.randint(1,10,5)

array([5, 8, 3, 5, 4])

In [20]:
# seed 변경
np.random.seed(0)
np.random.randint(1,10,5)

array([6, 1, 4, 4, 8])

---
---

## DIY: 도전 코딩 - numpy 정리 과제
- 생성된 마구잡이수를 조사하고 사용하기 
- 9월19일 자정 마감.

### [도전 1.] 0부터 9까지의 마구잡이 정수를 1000개 만들고 각 수의 빈도를 구하시오. 

In [29]:
# n1000=
n1000 = np.random.randint(0,10,1000)
n1000

array([5, 7, 0, 2, 3, 4, 8, 4, 3, 1, 8, 9, 1, 7, 2, 8, 5, 9, 3, 0, 0, 2,
       3, 1, 6, 8, 7, 0, 1, 9, 7, 0, 1, 4, 8, 1, 9, 0, 2, 6, 2, 5, 6, 3,
       5, 0, 0, 2, 1, 1, 1, 3, 8, 2, 2, 5, 4, 9, 4, 1, 3, 8, 4, 4, 0, 4,
       5, 6, 9, 4, 5, 6, 6, 6, 7, 1, 1, 0, 5, 9, 2, 1, 3, 1, 5, 0, 3, 2,
       0, 5, 4, 8, 3, 0, 7, 9, 6, 3, 4, 3, 7, 0, 9, 7, 3, 7, 6, 0, 4, 4,
       3, 2, 7, 0, 0, 0, 4, 2, 3, 7, 9, 6, 9, 1, 3, 2, 6, 2, 1, 6, 7, 0,
       3, 3, 6, 8, 0, 8, 9, 2, 9, 7, 6, 5, 8, 2, 6, 0, 6, 9, 5, 4, 0, 1,
       8, 8, 6, 9, 5, 5, 1, 8, 5, 9, 4, 8, 4, 4, 7, 1, 9, 0, 1, 6, 8, 3,
       1, 3, 6, 3, 5, 0, 3, 5, 1, 3, 8, 0, 7, 3, 3, 2, 4, 8, 8, 0, 7, 8,
       0, 8, 6, 4, 2, 3, 0, 3, 1, 1, 6, 7, 8, 4, 9, 0, 4, 0, 9, 9, 8, 7,
       1, 9, 6, 7, 7, 5, 7, 8, 1, 1, 9, 3, 9, 3, 3, 5, 8, 7, 3, 9, 0, 3,
       9, 7, 0, 1, 3, 8, 0, 3, 5, 7, 1, 4, 5, 0, 1, 7, 9, 7, 3, 3, 9, 1,
       7, 1, 5, 6, 8, 4, 9, 2, 0, 6, 1, 7, 0, 5, 4, 7, 7, 4, 8, 0, 7, 7,
       6, 2, 2, 3, 2, 3, 5, 7, 2, 3, 7, 5, 7, 8, 9,

In [28]:
np.unique(n1000)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
# 각 수의 빈도

### [도전 2.] 0부터 9까지의 마구잡이 정수를 1000개 만들고 각 수가 처음 출현하는 인덱스를 구하시오.
> 0이 처음 나타날 때의 인덱스, 1이 처음 나타날 때의 인덱스, ... 

In [ ]:
# 각 수가 처음 출현하는 인덱스


In [ ]:
# n1000[index]

### [도전 3.] seed를 1234로 고정하고, 위의 도전1,2를 다시 해보시오. 

### [도전 4.] 0부터 999까지의 마구잡이 정수로 구성되는 28X28 이차원배열을 만드시오.
- 시드를 고정 : np.random.seed(1234)
1. 각 행의 최대값, 최소갑을 구하시오.
2. 배열 전체의 최대값, 최소값을 구하시오.
3. 배열전체의 최대값, 최소값의 index를 각각 찾으시오.

---
---

## python graphics
- matplotlib
> import matplotlib.pyplot as plt

### 무작위수 분포 그려보기

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.hist(n1000,label=range(0,10), color='red')
# plt.show()

### [도전] 균일분포와 정규분포를 비교하는 그림을 그리시오.

In [ ]:
plt.hist(np.random.rand(1000))

In [ ]:
plt.hist(np.random.randn(1000))

## 보충 코드

In [30]:
n1000 = np.random.randint(0,10,1000)

In [31]:
value, count= np.unique(n1000, return_counts=True)