<a href="https://colab.research.google.com/github/dayeong918/pdm011/blob/main/numpy/numpy_2_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy array

- 생성
- 구조 살펴보기
- 수학연산 (columnwise, rowwise)

In [ ]:
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]] # 2차원 리스트.
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# summarize the array shape
print(data.shape) #2행 3열.

#AttributeError: 'list' object has no attribute 'shape' / .shape(데이터의 크기, 구조 확인) , data가 리스트여서 오류.

[[1 2 3]
 [4 5 6]]
(2, 3)


## Print rows

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]] 
# data.shape # Error!
# convert to a numpy array
data = asarray(data) # numpy 배열 객체로 바뀐다.
# step through rows

for row in range(data.shape[0]):
	print(data[row])

[1 2 3]
[4 5 6]


In [ ]:
data.shape
data.shape[0],data.shape[1] # 튜플의 indexing, slicing.

(2, 3)

## Print columns

In [ ]:
# enumerate rows in a numpy array
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
print(data)
# step through columns
for col in range(data.shape[1]):
	print(data[:,col]) # print: 셀 열을 바꿔줌.

[[1 2 3]
 [4 5 6]]
[1 4]
[2 5]
[3 6]


---

## NumPy Array Operations By Row and Column
- axis=None: Apply operation array-wise.
- axis=0: Apply operation column-wise, across all rows for each column.
- axis=1: Apply operation row-wise, across all columns for each row.

In [ ]:
# sum values array-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by array
result = data.sum(axis=None) #배열에 sum이라는 함수를 설계했을 때, default axis option이 None이다.
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


### Axis=0 Column-Wise Operation (수직으로)

In [ ]:
# sum values column-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by column
result = data.sum(axis=0) 
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
[5 7 9]


### Axis=1 Row-Wise Operation (수평으로)

In [ ]:
# sum values row-wise
from numpy import asarray
# define data as a list
data = [[1,2,3], [4,5,6]]
# convert to a numpy array
data = asarray(data)
# summarize the array content
print(data)
# sum data by row
result = data.sum()
# summarize the result
print(result)

[[1 2 3]
 [4 5 6]]
21


---

## [Challenge]
- 3d-array
    * axis = 0
    * axis = 1
    * axis = 2
    * axis = (0,1)

## [DIY: 도전하기]

- 3차원 배열을 리스트로부터 만드시오.
- [참고: numpy_sum_axis](http://taewan.kim/post/numpy_sum_axis/)

In [40]:
# Make 3d-array in numpy
import numpy as np
#from numpy import asarray

data = [[[1,2,3], [4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18],[19,20,21],[22,23,24],[25,26,27]]]
print(type(data))
data = np.asarray(data)
print(data)

<class 'list'>
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]
  [13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]
  [25 26 27]]]


In [41]:
print(type(data))
print(data.ndim)
len(data), len(data[0]), len(data[0][0]) #깊이, 행, 열
print(data.shape)

<class 'numpy.ndarray'>
3
(1, 9, 3)
